language: python
sudo: false

env:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
  
before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  
install:
  - luarocks install lredux

branches:
  only:
    - master

script:
  - cd examples
  - lua5.1 main.lua
  - lua5.2 main.lua
  - lua5.3 main.lua

notifications:
  email:
    on_success: change
    on_failure: always
