language: c
sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - lua5.2
    - lua5.3

branches:
  only:
    - master

script:
  - lua5.1 example/main.lua
  - lua5.2 example/main.lua
  - lua5.3 example/main.lua
