language: c
sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
  
install:
  - luarocks install lredux

branches:
  only:
    - master

script:
  - cd examples
  - lua5.1 main.lua
  - lua5.2 main.lua
  - lua5.3 main.lua

notifications:
  email:
    on_success: change
    on_failure: always
