language: c
sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - lua5.2
    - lua5.3

branches:
  only:
    - master

script:
  - lua5.1 examples/main.lua
  - lua5.2 examples/main.lua
  - lua5.3 examples/main.lua
