language: c
sudo: false

install:
  - luarocks install lredux

addons:
  apt:
    packages:
    - lua5.1
    - lua5.2
    - lua5.3

branches:
  only:
    - master

script:
  - cd examples
  - lua5.1 main.lua
  - lua5.2 main.lua
  - lua5.3 main.lua

notifications:
  email:
    on_success: change
    on_failure: always
